import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { MODULE, MODULES_DOC, modulesDoc } from './modules.ts';

/** A set of text files: POSIX path relative to the root → content. */
export type Tree = ReadonlyMap<string, string>;

export const COPIES: ReadonlyMap<string, readonly string[]> = new Map(([
  ['.agents/skills/to-spec/no-debt.md', ['to-issue', 'implement-feature', 'implement-batch', 'implement-orchestrated', 'implement-backlog', 'pr-review', 'pr-review-batch'], ''],
  ['.agents/skills/pr-review/findings.md', ['pr-review-batch'], ''],
  ['.agents/scripts/task-brief.ts', ['to-issue'], 'scripts/'],
  ['.agents/scripts/brief.ts', ['to-issue'], 'scripts/'],
  ['.agents/scripts/pr-diff.ts', ['pr-review', 'pr-review-batch'], 'scripts/'],
  ['.agents/scripts/diff.ts', ['pr-review', 'pr-review-batch'], 'scripts/'],
  ['.agents/scripts/screenshots-to-branch.ts', ['implement-feature', 'implement-batch'], 'scripts/'],
  ['.agents/scripts/screenshots.ts', ['implement-feature', 'implement-batch'], 'scripts/'],
  ['.agents/scripts/clean-worktrees.ts', ['implement-batch', 'pr-review-batch'], 'scripts/'],
  ['.agents/scripts/worktrees.ts', ['implement-batch', 'pr-review-batch'], 'scripts/'],
  ['.agents/scripts/prove.ts', ['verify-synthominos'], 'scripts/'],
  ['.agents/scripts/doctor.ts', ['verify-synthominos'], 'scripts/'],
  ['.agents/scripts/proofs.ts', ['verify-synthominos'], 'scripts/'],
  ['.agents/scripts/browser.ts', ['verify-synthominos'], 'scripts/'],
] as const).map(([from, skills, folder]) =>
  [from, skills.map(skill => `.agents/skills/${skill}/${folder}${path.posix.basename(from)}`)]));

const MIRRORS: readonly (readonly [string, string])[] = [
  ['.agents/skills/', '.claude/skills/'],
  ['.agents/rules/', '.claude/rules/'],
];
const AGENT = /^agents\/([^/]+)\.md$/;
export const MANAGED_ROOTS = ['.claude/skills/', '.claude/rules/', '.claude/agents/', '.codex/agents/'] as const;
export const GENERATED_MARK = '<!-- Generated by `node .agents/scripts/sync.ts`';

const normal = (text: string) => text.replaceAll('\r\n', '\n');

function ruleGlobs(rule: string): string[] {
  const front = /^---\n([\s\S]*?)\n---\n/.exec(normal(rule));
  return front === null ? [] : [...front[1].matchAll(/^\s*-\s*"([^"]+)"/gm)].map(m => m[1]);
}

export function ruleFolders(rule: string): string[] {
  const dirs = ruleGlobs(rule).map(glob => {
    const parts = glob.split('/');
    const firstGlob = parts.findIndex(p => /[*?{[]/.test(p));
    const literal = firstGlob === -1 ? parts.slice(0, -1) : parts.slice(0, firstGlob);
    return literal.join('/');
  });
  const unique = [...new Set(dirs)].sort();
  return unique.filter(d => !unique.some(o => o !== d && (o === '' || d.startsWith(`${o}/`))));
}

export function codexAgent(name: string, contract: string): { readonly toml: string | null; readonly problems: readonly string[] } {
  const parts = /^---\n([\s\S]*?)\n---\n+([\s\S]*)$/.exec(normal(contract));
  if (parts === null) return { toml: null, problems: ['has no frontmatter'] };
  const [, front, body] = parts;
  const field = (key: string) => new RegExp(`^${key}:\\s*(.*)$`, 'm').exec(front)?.[1].trim();
  const quoted = /^"([^"\\]*)"$/.exec(field('description') ?? '');
  const problems = [
    ...(field('name') === name ? [] : [`\`name\` must be \`${name}\`, the name of the file`]),
    ...(quoted === null ? ['`description` must be one double-quoted line, with no quote and no backslash inside'] : []),
    ...(field('model') === undefined ? [] : ['pins a model: an internal agent inherits the model of the Owner']),
    ...(field('effort') === 'max' ? [] : ['must declare `effort: max`']),
    ...(body.includes("'''") ? ["holds `'''`, which a TOML literal string cannot carry"] : []),
  ];
  if (problems.length > 0) return { toml: null, problems };
  const toml = [
    `# Generated by \`node .agents/scripts/sync.ts\` from \`agents/${name}.md\`. Edit the source.`,
    `name = "${name}"`,
    `description = "${(quoted as RegExpExecArray)[1]}"`,
    'model_reasoning_effort = "max"',
    'sandbox_mode = "workspace-write"',
    '',
    "developer_instructions = '''",
    `${body.trimEnd()}\n'''`,
    '',
  ].join('\n');
  return { toml, problems };
}

const ruleBody = (rule: string) => normal(rule).replace(/^---\n[\s\S]*?\n---\n+/, '');

function ruleSection(rule: string, dir: string): string {
  const scope = ruleGlobs(rule).map(glob => `\`${glob}\``).join(', ');
  return `> Applies to ${scope}.\n\n${rebaseLinks(ruleBody(rule), '.agents/rules', dir)}`;
}

export const CONTRACT = /^specs\/([^_/][^/]*)\/\1\.md$/;

export function contractSection(capability: string, spec: string): string | null {
  const field = (name: string) => new RegExp(`^${name}:\\s*(\\S+)`, 'm').exec(spec)?.[1] ?? '';
  if (field('status') === 'superseded') return null;
  const title = /^# (.+)$/m.exec(ruleBody(spec))?.[1] ?? capability;
  const id = field('capability_id');
  const file = `specs/${capability}/${capability}.md`;
  return [
    `# ${title}`,
    '',
    `The contract of this folder is [\`${file}\`](../../${file}), \`${id}\`. Read it before a change`,
    `to what this capability does. A test title cites each criterion it verifies: \`AC-${id.slice(4)}-###\`.`,
    'The rules for all of `src/` are in [`src/AGENTS.md`](../AGENTS.md).',
    '',
  ].join('\n');
}

export function rebaseLinks(text: string, fromDir: string, toDir: string): string {
  return text.replace(/\]\((?![a-z]+:|#)([^)\s#]+)(#[^)\s]*)?\)/g, (_, target: string, anchor = '') =>
    `](${path.posix.relative(toDir, path.posix.join(fromDir, target))}${anchor})`);
}

export interface Plan { readonly files: ReadonlyMap<string, string>; readonly problems: readonly string[] }

export function planCopies(canonical: Tree): Plan {
  const files = new Map<string, string>();
  const problems: string[] = [];
  const source = new Map<string, string>([...canonical].map(([p, t]) => [p, normal(t)]));

  for (const [from, targets] of COPIES) {
    const text = source.get(from);
    if (text === undefined) {
      problems.push(`${from}: declared as a canonical copy, but it does not exist`);
      continue;
    }
    for (const to of targets) {
      files.set(to, text);
      source.set(to, text);
    }
  }
  const copyNames = new Map([...COPIES.keys()].map(p => [path.posix.basename(p), p]));
  const declared = new Set([...COPIES.values()].flat());

  for (const [p, text] of source) {
    for (const [from, to] of MIRRORS) if (p.startsWith(from)) files.set(to + p.slice(from.length), text);
    const agent = AGENT.exec(p)?.[1];
    if (agent !== undefined) {
      const codex = codexAgent(agent, text);
      problems.push(...codex.problems.map(problem => `${p}: ${problem}`));
      files.set(`.claude/agents/${agent}.md`, text);
      if (codex.toml !== null) files.set(`.codex/agents/${agent}.toml`, codex.toml);
    }
    if (p.startsWith('.agents/skills/')) {
      if (/\.\.\/[\w-]+\//.test(text)) problems.push(`${p}: reaches into another skill with \`../\`; carry a declared copy instead`);
      const canonicalOfName = copyNames.get(path.posix.basename(p));
      if (canonicalOfName !== undefined && canonicalOfName !== p && !declared.has(p)) problems.push(`${p}: has the name of \`${canonicalOfName}\` but is not a declared copy`);
    }
  }

  const byFolder = new Map<string, { sources: string[]; sections: string[] }>();
  const add = (dir: string, from: string, section: string) => {
    const folder = byFolder.get(dir) ?? { sources: [], sections: [] };
    folder.sources.push(from);
    folder.sections.push(section);
    byFolder.set(dir, folder);
  };
  for (const [p, text] of source) {
    const capability = CONTRACT.exec(p)?.[1];
    const section = capability === undefined ? null : contractSection(capability, text);
    if (section !== null) add(`src/${capability}`, p, section);
  }
  const rules = [...source].filter(([p]) => p.startsWith('.agents/rules/') && p.endsWith('.md'));
  for (const [p, text] of rules.sort(([a], [b]) => a.localeCompare(b))) {
    for (const dir of ruleFolders(text)) {
      if (dir === '') problems.push(`${p}: applies to the repo root, whose AGENTS.md is written by hand`);
      else add(dir, p, ruleSection(text, dir));
    }
  }
  for (const [dir, { sources, sections }] of byFolder) {
    const header = `${GENERATED_MARK} from ${sources.map(s => `\`${s}\``).join(', ')}. Edit the source. -->\n\n`;
    files.set(`${dir}/AGENTS.md`, header + sections.join('\n'));
  }
  const modules = modulesDoc(source);
  if (modules !== null) files.set(MODULES_DOC, modules);
  return { files, problems };
}

export interface Difference { readonly kind: 'missing' | 'different' | 'stale'; readonly path: string }

export function differences(plan: Plan, disk: Tree): Difference[] {
  const out: Difference[] = [];
  for (const [p, text] of plan.files) {
    const current = disk.get(p);
    if (current === undefined) out.push({ kind: 'missing', path: p });
    else if (normal(current) !== text) out.push({ kind: 'different', path: p });
  }
  for (const [p, text] of disk) {
    const managed = MANAGED_ROOTS.some(r => p.startsWith(r)) || (p.endsWith('AGENTS.md') && normal(text).startsWith(GENERATED_MARK));
    if (managed && !plan.files.has(p)) out.push({ kind: 'stale', path: p });
  }
  return out.sort((a, b) => a.path.localeCompare(b.path));
}

export interface Disk {
  read(): Tree;
  write(file: string, text: string): void;
  remove(file: string): void;
  log(line: string): void;
}

export function sync(args: readonly string[], disk: Disk): 0 | 1 {
  const tree = disk.read();
  const plan = planCopies(tree);
  for (const problem of plan.problems) disk.log(problem);
  const diffs = differences(plan, tree);
  if (args.includes('--check')) {
    for (const d of diffs) disk.log(`${d.kind}: ${d.path}`);
    if (diffs.length > 0) disk.log('Run `node .agents/scripts/sync.ts` and commit the result.');
    return diffs.length > 0 || plan.problems.length > 0 ? 1 : 0;
  }
  const changed = new Set(diffs.filter(d => d.kind !== 'stale').map(d => d.path));
  for (const [file, text] of plan.files) {
    if (!changed.has(file)) continue;
    disk.write(file, text);
    disk.log(`wrote ${file}`);
  }
  for (const d of diffs) {
    if (d.kind !== 'stale') continue;
    disk.remove(d.path);
    disk.log(`removed ${d.path}`);
  }
  return plan.problems.length > 0 ? 1 : 0;
}

const SKIPPED = new Set(['node_modules', '.git', 'dist', 'coverage', '.vercel', 'worktrees', '.stryker-tmp']);

function walk(root: string, dir: string): string[] {
  if (!existsSync(path.join(root, dir))) return [];
  const out: string[] = [];
  for (const entry of readdirSync(path.join(root, dir), { withFileTypes: true })) {
    const rel = dir === '' ? entry.name : `${dir}/${entry.name}`;
    if (entry.isDirectory()) {
      if (!SKIPPED.has(entry.name)) out.push(...walk(root, rel));
    } else {
      out.push(rel);
    }
  }
  return out;
}

export function realDisk(root: string): Disk {
  return {
    read() {
      const files = [
        ...walk(root, '.agents'), ...walk(root, 'agents'), ...MANAGED_ROOTS.flatMap(r => walk(root, r.slice(0, -1))),
        ...walk(root, '').filter(f => f.endsWith('/AGENTS.md')),
        ...walk(root, 'specs').filter(f => CONTRACT.test(f)),
        ...walk(root, 'src').filter(f => MODULE.test(f)),
        ...walk(root, path.posix.dirname(MODULES_DOC)).filter(f => f === MODULES_DOC),
      ];
      return new Map([...new Set(files)].map(f => [f, readFileSync(path.join(root, f), 'utf8')]));
    },
    write(file, text) {
      mkdirSync(path.dirname(path.join(root, file)), { recursive: true });
      writeFileSync(path.join(root, file), text);
    },
    remove: file => rmSync(path.join(root, file)),
    log: line => console.log(line),
  };
}
