import path from 'node:path';
import ts from 'typescript';

export const MODULES_DOC = 'docs/architecture/modules.md';
export const MODULE = /^src\/(?!.*__tests__\/).+(?<!\.d)\.tsx?$/;
const SHELL = 'shell';

const id = (text: string) => text.replace(/[^A-Za-z0-9]/g, '_');
const groupOf = (file: string) => (file.split('/').length > 2 ? file.split('/')[1] : SHELL);
const mermaid = (lines: readonly string[]) => ['```mermaid', 'flowchart LR', ...lines, '```', ''];
const unique = (lines: readonly string[]) => [...new Set(lines)].sort();

export function modulesDoc(tree: ReadonlyMap<string, string>): string | null {
  const sources = [...tree].filter(([file]) => MODULE.test(file));
  if (sources.length === 0) return null;
  const files = sources.map(([file]) => file);
  const edges = sources.flatMap(([from, text]) => ts.preProcessFile(text, true, true).importedFiles
    .map(imported => path.posix.join(path.posix.dirname(from), imported.fileName))
    .filter(to => files.includes(to))
    .map(to => [from, to] as const));
  const groups = unique(files.map(groupOf));

  const overview = [
    ...groups.map(group => `  ${id(group)}["${group}"]`),
    ...unique(edges.filter(([from, to]) => groupOf(from) !== groupOf(to)).map(([from, to]) => `  ${id(groupOf(from))} --> ${id(groupOf(to))}`)),
  ];

  const section = (group: string) => {
    const label = (file: string) => (groupOf(file) === group ? path.posix.basename(file) : groupOf(file));
    const node = (file: string) => {
      if (groupOf(file) !== group) return `  ${id(label(file))}[/"${label(file)}"/]`;
      return `  ${id(label(file))}["${label(file)}"]${file.endsWith('.tsx') ? ':::component' : ''}`;
    };
    const out = edges.filter(([from]) => groupOf(from) === group);
    return [
      `## ${group}`,
      '',
      ...mermaid([
        '  classDef component fill:#fde68a,stroke:#b45309,color:#000',
        ...unique([...files.filter(file => groupOf(file) === group), ...out.map(([, to]) => to)].map(node)),
        ...unique(out.map(([from, to]) => `  ${id(label(from))} --> ${id(label(to))}`)),
      ]),
    ];
  };

  return [
    '<!-- Generated by `node .agents/scripts/sync.ts` from the imports of `src/`. Edit the source. -->',
    '',
    '# Modules',
    '',
    'An arrow goes from a file to what it imports. The test files are not in the map. `shell` is',
    'the files at the root of `src/`. What passes between two capabilities, and why, is in',
    '[the capability map](./capabilities.md).',
    '',
    '## Capabilities',
    '',
    ...mermaid(overview),
    'In each map below, a yellow box is a component and a slanted box is another capability.',
    '',
    ...groups.flatMap(section),
  ].join('\n');
}
